package com.loicortola.controller.persistence;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEVICE".
 */
public class Device {

    private Long id;
    /** Not-null value. */
    private String deviceId;
    /** Not-null value. */
    private String deviceResolver;
    /** Not-null value. */
    private String name;
    private long icon;
    /** Not-null value. */
    private String host;
    private String key;

    public Device() {
    }

    public Device(Long id) {
        this.id = id;
    }

    public Device(Long id, String deviceId, String deviceResolver, String name, long icon, String host, String key) {
        this.id = id;
        this.deviceId = deviceId;
        this.deviceResolver = deviceResolver;
        this.name = name;
        this.icon = icon;
        this.host = host;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDeviceId() {
        return deviceId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /** Not-null value. */
    public String getDeviceResolver() {
        return deviceResolver;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceResolver(String deviceResolver) {
        this.deviceResolver = deviceResolver;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getIcon() {
        return icon;
    }

    public void setIcon(long icon) {
        this.icon = icon;
    }

    /** Not-null value. */
    public String getHost() {
        return host;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHost(String host) {
        this.host = host;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

}
